# Generated by Django 4.2.11 on 2024-10-03 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_alter_price_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Price',
            new_name='Price_By_Month',
        ),
        migrations.RenameField(
            model_name='price_by_month',
            old_name='price',
            new_name='price_by_month',
        ),
    ]
