# Generated by Django 4.2.11 on 2024-10-03 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_rename_price_price_by_month_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price_By_Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_by_day', models.FloatField(default=0.0)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks.stock')),
            ],
        ),
    ]
