# Generated by Django 4.2.11 on 2024-10-24 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_price_by_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='ticker',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
